### ISSUE TITLE
Hyperparameters on ferv39k

### ISSUE THREAD

**Issue by xunnnnnnnnnnnn** [muse1998/IAL-for-Facial-Expression-Recognition#1]
I am very interested in your work! I would like to know if there are any other parameters that need to be adjusted in FERV39K, besides the difference in sampling from DFEW.

I used your method a few days ago, but I only got 43% of WAR on FERV39K, so I would like to know if there are any other parameters that need to be adjusted. Many thanks!

**Comment by Delete12137** [comment]
Hello, have you successfully reproduced the results? Could you please share your code with me for reference? I would greatly appreciate it!
